services:
  - type: web
    name: freshguard-backend
    env: python
    pythonVersion: "3.10.13"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.app:app
    envVars:
      - key: FLASK_ENV
        value: production